# Generated by Django 4.2.1 on 2023-05-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('6 PM', '6 PM'), ('7 PM', '7 PM'), ('8 PM', '8 PM'), ('9 PM', '9 PM')]),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (4, 4), (6, 6)]),
        ),
    ]
