# Generated by Django 4.2.1 on 2023-05-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_time_alter_table_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='content',
            field=models.CharField(max_length=300),
        ),
    ]
