# Generated by Django 4.2.1 on 2023-05-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_menu_title_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_name',
            new_name='name',
        ),
    ]
