# Generated by Django 4.2.1 on 2023-05-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_rename_user_name_booking_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='username',
        ),
    ]
