# Generated by Django 4.2.1 on 2023-05-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_table_alter_booking_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='capaciy',
            new_name='capacity',
        ),
    ]
